//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .scheduler_transparent_event 
        ///{
        ///	opacity: 0.7;
        ///	filter: alpha(opacity=70);
        ///}
        ///.scheduler_transparent_event_inner  
        ///{
        ///	/*margin-right: 1px;*/
        ///	/*padding: 4px 4px 4px 4px;*/
        ///	font-size: 10px;
        ///	line-height: 1.1;
        ///	overflow: hidden;
        ///	
        ///	position: absolute;
        ///	top: 0px;
        ///	bottom: 1px;
        ///	left: 0px;
        ///	right: 0px;
        ///    font-weight: 600;
        ///	
        ///	color: #000;
        ///	/*background: #47afff;
        ///	border: 1px solid #1066a8;*/
        ///}
        ///
        ///.scheduler_transparent_event_hover .scheduler_transparent_event_inner 
        ///{
        ///}
        ///
        ///.scheduler_t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scheduler_transparent {
            get {
                return ResourceManager.GetString("scheduler_transparent", resourceCulture);
            }
        }
    }
}
